name: conserva
base: core24 
version: '1.0' 
summary: Command line pomodoro timer
description: |
  A simple, down to earth pomodoro timer with a command line interface, a system tray and libnotify integration.

grade: devel 
confinement: devmode 

parts:
  conserva:
    # See 'snapcraft plugins'
    source: https://github.com/Maldus512/conserva.git
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - cmake
      - pkg-config
      - libnotify-dev
      - libjsoncpp-dev
      - qt6-base-dev
      - libgdk-pixbuf2.0-dev
      - libgtk-3-dev
    stage-packages:
      - libnotify4
      - libjsoncpp25
      - libqt6widgets6
      - libqt6gui6
      - libqt6network6
      - libqt6core6
      - libqt6dbus6
      - libqt6svg6       # Often needed for tray icons
      - libx11-6
      - libxext6
      - libxtst6
      - libglib2.0-0

apps:
  conserva:
    command-chain:
      - snap/command-chain/desktop-launch
    command: usr/bin/conserva
    extensions: [kde-neon-6]
    plugs: [desktop, desktop-legacy, dbus]
    bus: session
    dbus-name: com.github.Maldus512.conserva
